### ISSUE TITLE
Suggestions not being drawn over game

### ISSUE THREAD

**Issue by kuboson** [MgAl2O4/FFTriadBuddy#26]
Hi! I'm attempting to use the Play: Screenshot mode, and while the program detects the cards correctly, it doesn't provide the play suggestions by drawing a rectangle over the card (which I assume is meant to happen based on a screenshot I saw). This is what I see:

![image](https://user-images.githubusercontent.com/82656617/115023194-5a3b3c00-9eb6-11eb-82e8-6065b571782e.png)

What can I do to help troubleshoot this? In case it matters, I have dual monitors, however am running both FFXIV and FFTriadBuddy on the same one. Tried both XIVLauncher and the official launcher. DPI scaling is disabled in ffxiv_dx11.exe and in-game.

One thing I noticed, is when activating the checkbox to enable the overlay - it appears in the bottom center of the screen, but when I click Capture, it moves to the far left edge of the screen. I don't know if this is intentional behavior or an issue due to multiple montiors.

![image](https://user-images.githubusercontent.com/82656617/115024324-d7b37c00-9eb7-11eb-8b90-a692a18947b0.png)

**Comment by MgAl2O4** [comment]
Overlay is supposed to reposition on capture, to match current monitor. Moving far away suggests that either reading screen data failed (unlikely) or game window (maybe?)

Game launcher doesn't matter, tool is supposed to interact with game window, identified by ffxiv_dx11.exe process. Either launcher will be fine. Historically, I had A LOT of issues with DPI scalling, but since it's 100%, I can't blame it anymore :(

Let's start with checking log file, maybe there's something useful? By default, it will be saved in %localappdata%\FFTriadBuddy\ folder, file: outputLog.txt. Please find and upload it, hope to see something about game window sizes inside.

**Comment by kuboson** [comment]
[outputLog.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6325240/outputLog.txt)

My main display is 3840x2160, but I'm running FFXIV in a secondary 1920x1080 display, in windowed mode.

**Comment by MgAl2O4** [comment]
Is the second screen positioned to the left of main one? Log shows window position at X=-1928, which probably confuses overlay moving code. Can you swap their positions as an experiment? (right click on desktop > Display Settings from context menu > drag & drop monitor around on the fancy preview)

Debug build with additional logging about screen bounds:

[debug.zip](https://github.com/MgAl2O4/FFTriadBuddy/files/6325349/debug.zip)

**Comment by kuboson** [comment]
>Is the second screen positioned to the left of main one? 

It is, yes. I moved it to the right and ran the debug build, here is the log for that:
[outputLog-swapped.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6325390/outputLog-swapped.txt)
The overlay moved to the bottom-right corner of the screen when I clicked Capture this time.

And here is the log for 2nd monitor on the left:
[outputLog.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6325426/outputLog.txt)

There is another issue I noticed which I'm not sure whether is related: The overlay only appears when launching FFTriadBuddy from my main display (the one FFXIV is not on). If I run it from the secondary display, it doesn't appear, even after moving it back to the main display. Happens regardless of monitor order. Here's a log for that:
[outputLog.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6325478/outputLog.txt)

Let me know if there's anything else I can do!

**Comment by MgAl2O4** [comment]
Multi monitor code was based on guess work quite long time ago :D
I think I know what the issue is, but need to experiment myself a bit (and make a trial account with access to triple triad, lol) before updating tool for everyone.

Here's what I think should solve the problem (remove code messing with overlay coords) - not tested, but it can only improve since you're already at broken state :(

[debug2.zip](https://github.com/MgAl2O4/FFTriadBuddy/files/6325644/debug2.zip)

**Comment by kuboson** [comment]
No problem, I appreciate you taking the time to look into this :)

Unfortunately that build causes the overlay to not show at all, but it does appear at the top-left corner of the screen for a split second before disappearing. Here is the log, although there's not much in it:
[outputLog.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6325835/outputLog.txt)

**Comment by MgAl2O4** [comment]
One last try before postponing to next 3-ish days - until I can experiment myself :/

[debug3.zip](https://github.com/MgAl2O4/FFTriadBuddy/files/6326036/debug3.zip)

**Comment by kuboson** [comment]
The overlay displays again, but the suggestions still don't get drawn.
[outputLog.txt](https://github.com/MgAl2O4/FFTriadBuddy/files/6326140/outputLog.txt)

Some good(?) news though: Upon pressing Capture, the overlay now moves directly under the middle of the game board (previously it went to the left edge of the screen). The program still needs to be ran from the primary display for it to show.

![image](https://user-images.githubusercontent.com/82656617/115045865-d2adf700-9ece-11eb-8974-b38a912d70e9.png)

**Comment by MgAl2O4** [comment]
Welp, let's leave this one open for now, will get back to it in a few days :<

**Comment by kuboson** [comment]
Sounds good, let me know if you need me to test anything! ^^

**Comment by MgAl2O4** [comment]
Fixed in v50.

Couldn't repro any issues with overlay drawing depending on which monitor program was started on, maybe fixed as well? Closing for now.

**Comment by kuboson** [comment]
I can confirm it is fixed, thank you!

> Couldn't repro any issues with overlay drawing depending on which monitor program was started on, maybe fixed as well?

This is still broken, but it's no big deal for me.

Thanks again!
